GastosControl/Controllers/AuthController.cs
using GastosControl.Application.Services;
using GastosControl.Domain.Entities;
using GastosControl.Domain.Interfaces;
using GastosControl.Infrastructure.Persistence;
using GastosControl.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GastosControl.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;
        private readonly ApplicationDbContext _context;

        public AuthController(IUserService userService, ApplicationDbContext context)
        {
            _userService = userService;
            _context = context;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var user = await _userService.AuthenticateAsync(model.Login, model.Password);

            if (user == null)
            {
                ModelState.AddModelError("", "Credenciales inválidas");
                return View(model);
            }

            // Guardar usuario en sesión
            HttpContext.Session.SetInt32("UserId", user.Id);
            HttpContext.Session.SetString("UserRole", user.Role);
            HttpContext.Session.SetString("UserName", user.FirstName);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Identification,FirstName,LastName,Login,Password,BirthDate,Address,Email,Phone")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                var newUser = await _userService.AuthenticateAsync(user.Login, user.Password);
                if (user == null)
                {
                    return RedirectToAction(nameof(Index));
                }
                HttpContext.Session.SetInt32("UserId", newUser.Id);
                HttpContext.Session.SetString("UserRole", newUser.Role);
                HttpContext.Session.SetString("UserName", newUser.FirstName);

                return RedirectToAction("Index", "Home");
            }
            return View(user);
        }
    }
}

GastosControl/Controllers/BudgetController.cs
using GastosControl.Application.Interfaces;
using GastosControl.Application.Services;
using GastosControl.Domain.Entities;
using GastosControl.Infrastructure.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace GastosControl.Controllers
{
    public class BudgetController : Controller
    {
        private readonly IUserBudgetService _repository;
        private readonly IExpenseService _expenseService;
        private readonly ApplicationDbContext _context;

        public BudgetController(IExpenseService expenseService, IUserBudgetService repository, ApplicationDbContext context)
        {
            _repository = repository;
            _context = context;
            _expenseService = expenseService;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Summary(string BudgetMonth)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("Login", "Auth");

            var date = BudgetMonth.Split('-');
            var year = int.Parse(date[0]);
            var month = int.Parse(date[1]);

            var resumen = await _expenseService.GetMonthlyBudgetSummaryAsync(userId.Value, month, year);
            ViewBag.Month = month;
            ViewBag.Year = year;
            return View(resumen);
        }
    }

}

GastosControl/Controllers/DepositController.cs
using GastosControl.Application.Interfaces;
using GastosControl.Domain.Entities;
using GastosControl.Helpers;
using GastosControl.Infrastructure.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GastosControl.Controllers
{
    [AuthorizeSession]
    public class DepositController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IDepositService _depositService;

        public DepositController(ApplicationDbContext context, IDepositService depositService)
        {
            _context = context;
            _depositService = depositService;
        }

        // GET: Deposit
        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("Login", "Auth");

            var deposits = await _context.Deposits
                .Include(d => d.MonetaryFund)
                .Where(d => d.UserId == userId)
                .ToListAsync();

            return View(deposits);
        }


        // GET: Deposit/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deposit = await _context.Deposits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deposit == null)
            {
                return NotFound();
            }

            return View(deposit);
        }

        // GET: Deposit/Create
        public IActionResult Create()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("Login", "Auth");

            ViewBag.MonetaryFundId = new SelectList(
                _context.MonetaryFunds.Where(f => f.UserId == userId),
                "Id", "Name"
            );
            return View();
        }

        // POST: Deposit/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MonetaryFundId,Amount")] Deposit deposit)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("Login", "Auth");

            if (ModelState.IsValid)
            {
                deposit.UserId = userId.Value;
                deposit.Date = DateTime.Now;

                await _depositService.AddAsync(deposit);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.MonetaryFundId = new SelectList(
                _context.MonetaryFunds.Where(f => f.UserId == userId), "Id", "Name", deposit.MonetaryFundId
            );
            foreach (var modelState in ViewData.ModelState)
            {
                foreach (var error in modelState.Value.Errors)
                {
                    Console.WriteLine($"Error en '{modelState.Key}': {error.ErrorMessage}");
                }
            }

            return View(deposit);
        }

        // GET: Deposit/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deposit = await _context.Deposits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deposit == null)
            {
                return NotFound();
            }

            return View(deposit);
        }

        // POST: Deposit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var deposit = await _context.Deposits.FindAsync(id);
            if (deposit != null)
            {
                _context.Deposits.Remove(deposit);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepositExists(int id)
        {
            return _context.Deposits.Any(e => e.Id == id);
        }
    }
}

GastosControl/Controllers/UserController.cs
using GastosControl.Domain.Entities;
using GastosControl.Helpers;
using GastosControl.Infrastructure.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GastosControl.Controllers
{
    [AuthorizeSession]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: User
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: User/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: User/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Identification,FirstName,LastName,Login,Password,BirthDate,Address,Email,Phone")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Identification,FirstName,LastName,Login,Password,BirthDate,Address,Email,Phone")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

GastosControl/Views/Shared/_Layout.cshtml
@{
    var userName = Context.Session.GetString("UserName");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GastosControl</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GastosControl.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Control De Gastos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @{
                        var userRole = Context.Session.GetString("UserRole");
                    }
                    <ul class="navbar-nav flex-grow-1">
                        @if (!string.IsNullOrEmpty(userName))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ExpenseType" asp-action="Index">Tipos de Gasto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="MonetaryFund" asp-action="Index">Fondos monetarios</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="UserBudget" asp-action="Index">Presupuesto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Expense" asp-action="Index">Gastos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Deposit" asp-action="Index">Deposito</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Budget" asp-action="Index">Mis movimientos</a>
                        </li>
                        @if (userRole == "Admin")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movement" asp-action="Index">Movimientos de usuarios</a>
                        </li>
                            }
                        }
                    </ul>
                </div>
                @if (!string.IsNullOrEmpty(userName))
                {
                    <div class="text-end text-muted me-3">
                        Hola, @userName |
                        <a asp-controller="Auth" asp-action="Logout">Cerrar sesión</a>
                    </div>
                }
            </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - GastosControl - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>